MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',  include("MyBlog_blog.urls")),
]

MyBlog/MyBlog_blog/urls.py
from django.conf.urls import url
from MyBlog_blog.views import IndexView, AboutView, BlogDetailView, ContactView

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


app_name = 'MyBlog_blog'

urlpatterns = [
    url(r'^$', IndexView, name='homepage'),
    url(r'^hakkinda/', AboutView, name='about'),
    url(r'^blog/(?P<id>\d+)/$', BlogDetailView, name='blog_detail'),
    url(r'^iletisim/', ContactView, name='contact'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyBlog/MyBlog_blog/models.py
from django.db import models

class Blog(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Kullanıcı Adı")
    title = models.CharField(max_length=120, verbose_name="Başlık")
    content = models.TextField(verbose_name="İçerik")
    thumbnail = models.ImageField(blank=True, null=True, verbose_name="Blog Thumbnail", upload_to='images/blog/thumbnail/')
    created_date = models.DateTimeField(auto_now=True, verbose_name="Oluşum Tarihi")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Bloglar'

class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name="Ad Soyad")
    email = models.EmailField(verbose_name='Email Adresi', blank=False, null=False)
    title = models.CharField(max_length=200, verbose_name="Başlık")
    message = models.TextField(blank=True, null=True, verbose_name='Mesaj')
    has_consented = models.BooleanField(null=True, verbose_name='Secim')
    created_date = models.DateTimeField(auto_now=True, verbose_name="Tarih")

    class Meta:
        verbose_name = 'İletişim'
        verbose_name_plural = 'İletişimler'

    def __str__(self):
        return self.title

MyBlog/MyBlog_blog/forms.py
from django import forms
from django.forms import ModelForm, TextInput, CheckboxInput
from MyBlog_blog.models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "title", "message","has_consented"]
        widgets = {
            'name': TextInput(attrs={'id': 'input_name','class':'form-control', 'name': 'your-name', 'placeholder':'Name'}),
            'email': TextInput(attrs={'id': 'input_email','class':'form-control', 'name': 'your-email', 'placeholder':'Email'}),
            'subject': TextInput(attrs={'id': 'subject','class':'form-control', 'name': 'your-subject', 'placeholder':'Subject'}),
            'message': TextInput(attrs={'id': 'subject','class':'form-control', 'name': 'your-message', 'placeholder':'Message'}),
            'has_consented':forms.CheckboxInput(attrs={'id': 'checkbox'}),
}

MyBlog/MyBlog_blog/views.py
from django.shortcuts import render, redirect, HttpResponse
from MyBlog_blog.models import Blog
from MyBlog_blog.forms import ContactForm

from django.contrib.auth.decorators import login_required


def IndexView(request):
    blog = Blog.objects.order_by('-created_date')
    context = {
        "blog": blog
    }
    return render(request, 'web/index.html', context)

def AboutView(request):
    return render(request, 'web/about.html')

def BlogDetailView(request,id):
    blog = Blog.objects.get(id=id)
    context = {
        "blog": blog
    }
    return render(request, 'web/blog-detail.html',context)

def ContactView(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        Contact = form.save(commit=True)
        return redirect("MyBlog_blog:contact")
    context = {
        "form": form
    }
    return render(request, 'web/contact.html',context)

@login_required
def ExampleLoginRequiredView(request):
    return render(request, 'web/index.html')

MyBlog/templates/web/about.html
{% extends "web/base.html" %}
{% load static %}
{% block headerTitle %}Hakkında {% endblock headerTitle %}

{% block content %}
<h1>Hakkında Sayfası</h1>
{% endblock content %}

MyBlog/templates/web/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% block headerTitle %} {% endblock headerTitle %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    {% block pageHeader %}

    {% endblock pageHeader %}
  </head>
  <body>
  {% include "web/components/header.html" %}
    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% block pageJs %}

    {% endblock pageJs %}
  </body>
</html>

MyBlog/templates/web/components/header.html
<nav class="navbar navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'MyBlog_blog:homepage'  %}">Blog</a>
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'MyBlog_blog:about'  %}">Hakkımızda</a>
            </li>
            
          </ul>
        </div>
</nav>

MyBlog/templates/web/contact.html
{% extends "web/base.html" %}
{% load static %}
{% block headerTitle %}İletişim {% endblock headerTitle %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
   <!-- <p>
        <label for="checkbox">I confirm...</label>
        <input type="checkbox" name="has_consented" id="checkbox">
    </p>-->
    <button type="submit" class="btn btn-success">
        Kaydet
    </button>
</form>
{% endblock content %}

MyBlog/templates/web/index.html
{% extends "web/base.html" %}
{% load static %}
{% block headerTitle %}EasyBlog {% endblock headerTitle %}

{% block content %}
<h1>Index Template'inden yazıldı</h1>

{% for blogs in blog %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="#"><h2 class="mt-4">{{blogs.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
        {{blogs.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{blogs.created_date}}</p>
      <hr>
      <!-- Preview Image -->
       <!-- Preview Image -->
      {% if blogs.thumbnail %}
      <a href="{% url 'MyBlog_blog:blog_detail' id=blogs.id %}"><img class="img-fluid rounded" src="{{blogs.thumbnail.url}}" alt=""></a>
      {% endif %}
    
      <hr>
      <a style ="float : right;" href="#" class ="btn btn-danger">Devamını Oku</a>
      <hr>
         
        </div>
      </div>
      </div>

{% endfor %}
{% endblock content %}